tonycoco/heroku-buildpack-ember-cli

- config/nginx.conf.erb
Currently, setting FORCE_HTTPS to false is the same as setting it to true (or any other string)
> Only force https if FORCE_HTTPS is true

- config/nginx.conf.erb
This prevents caching `index.html` across deploys so users get the latest
`index.html` and fingerprinted assets.
`index.html` was being cached so that after a deploy you would receive a cached file. It would require a full page refresh to get the latest code. I've been running this change in production for a while, and it solves the problem. `expires -1` [correctly sets `Cache-Control: no-cache`](http://nginx.org/en/docs/http/ngx_http_headers_module.html).
> Properly set the `Cache-Control` to `no-cache` for index.html

- bin/compile
- The after_hook may need the built app (Actually we are using it to deploy some assets)
> Moved after_hook after the build process

- config/nginx.conf.erb
it was rewriting to http even though the request was https. this checks
for force_https and if true, rewrites to https
> add support for https and prerender

- config/nginx.conf.erb
This caused me a big headache. I had a file at public/folder/index.html, and when I visited /folder from the main page of our site, I was redirected to the page, but with the Nginx listening port added on. Since nginx is running behind a Heroku reverse proxy, this is obviously undesirable and the page did not load.
This config change prevents the port Nginx is listening on from appearing in the URL during a redirect.
> Remove port from redirection

- config/nginx.conf.erb
The X in headers is deprecated http://tools.ietf.org/html/rfc6648.
I don't know how the `X-Prerender-Token` works, so I kept it in.
```erb
<% if ENV["PRERENDER_TOKEN"] %>
proxy_set_header X-Prerender-Token <%= ENV["PRERENDER_TOKEN"] %>;
<% end %>
```
> Remove deprecated "X-" in headers

- config/nginx.conf.erb
`client_max_body_size` is fairly low by default in nginx. This comes up frequently enough that I made it an env var. Usage example: `CLIENT_MAX_BODY_SIZE=20M`
> Support custom client_max_body_size

- config/nginx.conf.erb
There needs to be an = in order to set the value. Without it, deploys fail and the value is not inserted from ENV.
> Fix nginx client_max_body_size erb line

- README.md
I have a before hook that installs sass, that just started failing yesterday with the following messages
```
remote: -----> Before hook detected. Running...
remote: WARNING:  You don't have /tmp/build_cc71047275a4e3d2053b5732bc129d7f/.gem/ruby/2.2.0/bin in your PATH,
remote: 	  gem executables will not run.
remote: Successfully installed sass-3.4.13
remote: 1 gem installed
remote: -----> Caching ruby gems directory for future builds
remote: -----> Building Ember CLI application production distribution
remote:        version: 0.2.0
remote:        Could not find watchman, falling back to NodeWatcher for file system events
remote: [broccoli-ruby-sass] Error: spawn sass ENOENT
remote:        BuildingBuilding.Building..Building...BuildingBuilding.Build failed.
remote:        spawn sass ENOENT …
```
> Change ruby version in before_hook to 2.2.0

- README.md
- config/nginx.conf.erb
As discussed in https://github.com/tonycoco/heroku-buildpack-ember-cli/issues/83 I added support for the CloudFlare SSL header. Updated the docs with links to the official documentation.
I saw nowhere in the nginx config file comments, so I left the comments out of the pull request, I'll add it here so we can always find it.
```erb
<% if ENV["FORCE_HTTPS"] && ENV["FORCE_HTTPS"] == "true" %>
<%# Set default value for CloudFlare %>
set $cloudflare NO;
<%# This matches http and https ($http_cf_visitor: {"scheme": "https"})%>
if ($http_cf_visitor ~* 'http') {
set $cloudflare YES;
}
<%# Redirect when is matches "http" (with quotes) %>
if ($http_cf_visitor ~* '"http"') {
return 301 https://$host$request_uri;
}
<%# Only redirect when CloudFlare is false %>
set $cloudflare_heroku "${cloudflare}"; …
```
> Add force HTTPS support for CloudFlare

- README.md
- bin/compile
Ember-cli 1.13.5 (https://github.com/ember-cli/ember-cli/releases/tag/v1.13.5) recommends using:
``` npm install--no-optional``` to skip installing native libraries.  I believe this will speed up heroku installation significantly 
As far as I can tell most of these optional native packages are *very* optional particularly in a heroku non-developer environment.  If that is a bad assumption I can modify further to make this a build variable dependent action.
> When installing NPM packages use the --no-optional flag

- README.md
- bin/compile
Sometimes during major Ember or EmberCLI upgrades midway through a project, it becomes necessary to rebuild NPM or Bower components in the Heroku slug.  Unfortunately, clearing the NPM or Bower caches doesn't always do the trick.
This pull request allows the user to simply and easily push a NO/OP change to Heroku that forces a rebuild.
Rebuilds now are as easy as:
heroku config:set REBUILD_ALL=true
git commit -am 'rebuild' --allow-empty
git push heroku master
heroku config:unset REBUILD_ALL
> Force rebuilds of NPM and Bower packages.

- README.md
- config/nginx.conf.erb
Setting `IP_WHITELIST` in your Herkou application to a comma delimited list of IP addresses or CIDR blocks will restrict access to your application to only those values.
> Add IP whitelist

- bin/compile
New version of bower broke my deploy.  I think this fixes it, but I'm not sure if it's the best way to go about  this.
> Lock bower version to 1.5.3

- bin/compile
In the case where you use rebuild all bower will always fail install check.
This causes problems if you use shrinkwrap in combination with rebuild all.
The fix:
* Move bower installed check to after npm install
* Add node_modules/.bin to PATH
* Add check for bower using type function
* Set bower executable in path after installing
> Make sure to use existing bower

- config/nginx.conf.erb
WhatsApp has currently link previews in their app, we want to show them the prerendered version of the page. I checked for their user agent and it looks like this
```
WhatsApp/2.12.15/i
```
So the keyword `whatsapp` should be good enough.
> Add WhatsApp to prerender bots

- config/nginx.conf.erb
- config/nginx.d/README.md
Hi there.
Given that there seemed to be no middle ground between setting a few ENV vars or replacing the entire NGINX config, I thought it might be nice if we dynamically included a config directory that allows the buildpack user to add fragments of NGINX config without having to replace the buildpack config and potentially lose any further enhancements made by the community.
Therefore; I've added `config/nginx.d/` and an include line in the `server` declaration of the main NGINX config.  If you create a file ending in `.conf` and drop it in this directory then NGINX will include the config in it when it fires up.
> Add NGINX config fragments.

- README.md
If `NODE_ENV=production`, this is required.
> Add note about setting NPM_CONFIG_PRODUCTION=false

- README.md
- config/nginx.conf.erb
This allows Nginx to respond correctly to `.well-known/acme-challenge` that is invoked from the Let's Encrypt `certbot` command. By setting the `ACME_CHALLENGE` env var, and following the steps outlined in the updated README, it becomes a simple process to add/renew a Let's Encrypt SSL certificate.
> Add support for LetsEncrypt via ACME_CHALLENGE

- README.md
- bin/compile
This allows you to set a custom NGINX_URL so you can download a later version of nginx built on Heroku. 
The process for building on Heroku is a bit involved, but the steps are below (for anyone else wanting to do it):
* add the latest nginx build to your repo (download from https://nginx.org/en/download.html) and deploy to Heroku
* `heroku run bash` and un-tar.
* build using:
```
cd <location of untar'd nginx dist>
./configure
make
```
* scp the built binary (nginx) to another server
* scp off that other server to local machine
* download the tar that this buildpack installs by default (https://s3.amazonaws.com/devmynd-github/heroku-nginx-1.6.0.tar.gz)
* replace the nginx binary with the newly built binary from Heroku, re-tar and upload to your own S3 bucket, making it public. 
* set …
> Custom nginx

- README.md
Installing heroku repo via
```
heroku plugins:install https://github.com/heroku/heroku-repo.git 
```
will end up here
```
!    `repo` is not a heroku command.
```
The correct way is 
heroku plugins:install heroku-repo
https://github.com/heroku/heroku-repo/issues/40
> Proper way to install heroku-repo

- README.md
It's a small thing, but _techincally_ the heroku ember buildpack is not one of Heroku's official buildpacks.  It is instead an open source initiative we are trying out while evaluating how best to more officially support ember and other single pages apps on our platform.  We are still excited to get people using and contributing to our buildpack, but we want to set expectations appropriately.
> Remove word official from reference to heroku buildpack
